inherit_gem:
  scc-codestyle:
    - default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Gemfile
    - config.ru
  Exclude:
    - .bundle/**/*
    - vendor/**/*
    - package/*
    - Rakefile

Rails:
  Enabled: false